name: Example Action

on:
  push:
    branches:
      - main  # Triggers on a push to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1001929@ds.study.iitm.ac.in
        run: echo "Hello, world!"
